const https=require("https"),http=require("http"),cron=require("node-cron"),TB_BASE="https://www.terabox.com",TB_APP_ID="250528",TB_UA="Mozilla/5.0 (Linux; Android 14; CPH2581) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36",PING_INTERVAL_MINUTES=parseInt(process.env.PING_INTERVAL||"1"),WORKER_URL=process.env.WORKER_URL||"",PORT=parseInt(process.env.PORT||"3000"),NDUS=process.env.NDUS||"",BROWSERID=process.env.BROWSERID||"";
function log(e,m){const t=new Date().toLocaleString("id-ID",{timeZone:"Asia/Jakarta"});console.log(`[${t}] ${e} ${m}`)}
function fetchWithRedirect(u,c,mx=10){return new Promise((rs,rj)=>{let cu=u,rd=0;const ac=[],al=[];
function df(fu){const p=new URL(fu),hs=p.protocol==="https:",hm=hs?https:http;
const headers={"User-Agent":TB_UA,Accept:"text/html,application/xhtml+xml","Accept-Language":"id-ID,id;q=0.9,en;q=0.8"};if(c)headers.Cookie=c;const re=hm.request(fu,{method:"GET",headers,rejectUnauthorized:false},(r)=>{const sc=r.headers["set-cookie"];if(sc)ac.push(...(Array.isArray(sc)?sc:[sc]));const l=r.headers.location;if((r.statusCode===301||r.statusCode===302||r.statusCode===307||r.statusCode===308)&&l){if(rd>=mx)return rs({statusCode:r.statusCode,finalUrl:fu,cookies:ac,locations:al,tooManyRedirects:true});rd++;al.push(l);r.resume();return df(new URL(l,fu).href)}let b="";r.setEncoding("utf8");r.on("data",c=>b+=c);r.on("end",()=>rs({statusCode:r.statusCode,finalUrl:fu,cookies:ac,locations:al,body:b.substring(0,5000),hasLogin:/passport|login-form|signin|login\.php/i.test(b),isIndonesian:/indonesian/i.test(fu)||/indonesian/i.test(b.substring(0,500))}))});re.on("error",e=>rj(e));re.setTimeout(15000,()=>{re.destroy();rj(new Error("timeout"))});re.end()}df(cu)})}
function parseCookies(sc){const r={};for(const ra of sc){const kv=ra.split(";")[0].trim(),eq=kv.indexOf("=");if(eq>0){const n=kv.substring(0,eq).trim(),v=kv.substring(eq+1).trim();if(n&&v&&v!="deleted")r[n]=v}}return r}
function parseShareUrl(u){const ps=[/\/s\/([a-zA-Z0-9_-]+)/,/surl=([a-zA-Z0-9_-]+)/,/\/sharing\/link\?surl=([a-zA-Z0-9_-]+)/,/shorturl=([a-zA-Z0-9_-]+)/];for(const x of ps){const m=u.match(x);if(m)return m[1]}try{const x=new URL(u),pp=x.pathname.split("/").filter(Boolean);if(pp.length>=2&&pp[0]==="s")return pp[1];return pp[pp.length-1]}catch(_){return null}}
function formatSize(b){if(!b||b===0)return"0 B";if(b>1073741824)return(b/1073741824).toFixed(1)+" GB";if(b>1048576)return(b/1048576).toFixed(1)+" MB";if(b>1024)return(b/1024).toFixed(1)+" KB";return b+" B"}
function getCookieStr(){return `ndus=${NDUS}; browserid=${BROWSERID}; lang=id; PANWEB=1`}
function getApiHeaders(){return{"User-Agent":TB_UA,Cookie:getCookieStr(),Accept:"application/json, text/plain, */*","Accept-Language":"en-US,en;q=0.9,id;q=0.8",Referer:`${TB_BASE}/main?category=all`,Origin:TB_BASE}}
function apiFetch(up){return new Promise((rs,rjb)=>{const p=new URL(up),hs=p.protocol==="https:",hm=hs?https:http;const re=hm.request(up,{method:"GET",headers:getApiHeaders(),rejectUnauthorized:false},(r)=>{let b="";r.setEncoding("utf8");r.on("data",c=>b+=c);r.on("end",()=>{try{rs(JSON.parse(b))}catch(p){rs(null)}})});re.on("error",e=>rj(e));re.setTimeout(15000,()=>{re.destroy();rj(new Error("timeout"))});re.end()})}
let lp=null,pc=0,le=null;
async function ping(){if(!NDUS){le="NDUS not set";return{ok:false,error:"NDUS not set"}}try{pc++;const c=`ndus=${NDUS}; browserid=${BROWSERID}; lang=id; PANWEB=1`;log("🔆",`Ping #${pc} — loading page...`);const res=await fetchWithRedirect(`${TB_BASE}/main?category=all`,c);const nc=parseCookies(res.cookies),fd=new URL(res.finalUrl).hostname,isLn=res.finalUrl.includes("login")||res.finalUrl.includes("passport")||res.hasLogin;if(isLn){log("❌",`SESSION EXPIRED! ${res.finalUrl}`);le="Session expired";lp={ok:false,status:"expired",time:new Date().toISOString(),url:res.finalUrl};await notifyWorker({status:"expired",error:"Redirect to login"});return lp}const reg=res.isIndonesian?"🇮🇩 Indo":"🌍 Global";log("✅",`OK! HTTP ${res.statusCode} → ${fd} ${reg} | ${res.locations.length} redirects | ${Object.keys(nc).length} new cookies`);if(Object.keys(nc).length>0)log("🍪",`New: ${Object.keys(nc).join(", ")}`);lp={ok:true,status:"active",time:new Date().toISOString(),url:res.finalUrl,domain:fd,indonesian:res.isIndonesian,redirects:res.locations.length,newCookies:Object.keys(nc)};le=null;await notifyWorker({status:"active",region:res.isIndonesian?"id":"global"});return lp}catch(e){log("💥",`Error: ${e.message}`);le=e.message;lp={ok:false,status:"error",time:new Date().toISOString(),error:e.message};await notifyWorker({status:"error",error:e.message});return lp}}
async function notifyWorker(d){if(!WORKER_URL)return;try{const u=new URL("/ping",WORKER_URL),hs=u.protocol==="https:",hm=hs?https:http;const b=JSON.stringify({type:"keepalive",source:"suga-pinger",ping_count:pc,...d});await new Promise((rs=>{const re=hm.request(u.href,{method:"POST",headers:{"Content-Type":"application/json"},timeout:10000},(r)=>{r.resume();r.on("end",rs)});re.on("error",()=>rs());re.write(b);re.end()}))}catch(_){}}
async function handleList(su){if(!NDUS)return{success:false,error:"NDUS not set"};const sl=parseShareUrl(su);if(!sl)return{success:false,error:"Gagal parse URL"};try{const d=await apiFetch(`${TB_BASE}/api/shorturlinfo?app_id=${TB_APP_ID}&shorturl=${encodeURIComponent(sl)}&root=1`);if(!d||d.errno!==0){const e={111:"Link expired",105:"Need login",2:"File not found","-6":"Need login"};return{success:false,errno:d?.errno,error:e[d?.errno]||`errno=${d?.errno}`}}const fs=[];function ex(l){for(const i of l||[]){if(i.isdir==="1"){ex(i.list||[])}else{fs.push({filename:i.server_filename||i.filename,size_bytes:parseInt(i.size)||0,size:formatSize(parseInt(i.size)||0),fs_id:i.fs_id,md5:i.md5,path:i.path})}}}ex(d.list);return{success:true,shareid:d.shareid,uk:d.uk,file_count:fs.length,files:fs}}catch(e){return{success:false,error:`Network: ${e.message}`}}}
async function handleDownload(su,fi){if(!NDUS)return{success:false,error:"NDUS not set"};const sl=parseShareUrl(su);if(!sl)return{success:false,error:"Gagal parse URL"};try{const d=await apiFetch(`${TB_BASE}/share/download?app_id=${TB_APP_ID}&shorturl=${encodeURIComponent(sl)}&fid_list=[${fi}]`);if(!d||d.errno!==0){return{success:false,errno:d?.errno,error:`Download errno=${d?.errno}`}}const dl=d.dlink||d.list?.[0]?.dlink||"",fn=d.list?.[0]?.server_filename||d.list?.[0]?.filename||"file",sz=parseInt(d.list?.[0]?.size)||0;return{success:true,filename:fn,size:sz,size_formatted:formatSize(sz),dlink_direct:dl}}catch(e){return{success:false,error:`Network: ${e.message}`}}}
function jsonRes(r,d,s=200){r.writeHead(s,{"Content-Type":"application/json"});r.end(JSON.stringify(d,null,2))}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://localhost:${PORT}`);if(url.pathname==="/"||url.pathname==="/health"){res.writeHead(200,{"Content-Type":"application/json"});res.end(JSON.stringify({status:le?"degraded":"ok",ndus_configured:!!NDUS,last_ping:lp,ping_count:pc,uptime:process.uptime()},null,2));return}
if(url.pathname==="/ping"&&req.method==="POST"){ping().then(r=>{res.writeHead(200,{"Content-Type":"application/json"});res.end(JSON.stringify(r,null,2))});return}
if(url.pathname==="/list"&&req.method==="POST"){let b="";req.on("data",c=>b+=c);req.on("end",async()=>{try{const d=JSON.parse(b),su=d.u||d.url||d.share_url;if(!su)return jsonRes(res,{success:false,error:"url param required"},400);const r=await handleList(su);jsonRes(res,r,r.success?200:(r.errno?401:400))}catch(e){jsonRes(res,{success:false,error:"Invalid JSON"},400)}});return}
if(url.pathname==="/download"&&req.method==="POST"){let b="";req.on("data",c=>b+=c);req.on("end",async()=>{try{const d=JSON.parse(b),su=d.u||d.url||d.share_url,fi=d.fs_id;if(!su||!fi)return jsonRes(res,{success:false,error:"url & fs_id required"},400);const r=await handleDownload(su,fi);jsonRes(res,r.r.success?200:(r.errno?401:400))}catch(e){jsonRes(res,{success:false,error:"Invalid JSON"},400)}});return}
if(url.pathname==="/update-cookie&&&req.method==="POST"){let b="";req.on("data",c=>b+=c);req.on("end",()=>{try{const d=JSON.parse(b);process.env.NDUS=d.ndus||NDUS;process.env.BROWSERID=d.browserid||BROWSERID;log("🔆","NDUS updated");jsonRes(res,{ok:true})}catch(e){jsonRes(res,{error:"Invalid JSON"},400)}});return}
res.writeHead(404);res.end("Not found")});
server.listen(PORT,()=>{log("🚀",`Pinger started on port ${PORT}`);log("⏸",`Cron: every ${PING_INTERVAL_MINUTES} minutes`);log("🍪",`NDUS: ${NDUS ? NDUS.substring(0, 12) + "..." : "NOT SET!"}`);ping();cron.schedule(`*/${PING_INTERVAL_MINUTES} * * * *`,()=>ping());log("📣",`Next ping in ${PING_INTERVAL_MINUTES} minutes`)});